### ISSUE TITLE
How to use loadImage(unsigned char* image) function?

### ISSUE THREAD

**Issue by huijinH** [nkristina/ImageEditor#1]
loadImage() parameter should be what? I give imagepath is doesn't work. tks.

**Comment by nkristina** [comment]
`loadImage()` parameter is `char*` made by _Test.obj_ file. It is working on taking needed information from _.bmp_ format.

If you want to test the code on your example you should put your picture in the folder where you cloned the repo and made a project. It is important to name the picture "**MyExampe.bmp**". You do not need to specify the path anywhere.

In _main.cpp_, your example is under case 0. There you can choose what to do with the picture.

Take a look at the updated _README.md_. 😃

**Comment by huijinH** [comment]
Hello, I still don't know how to use it. Please help me to see my operation. Can you post the code? Because the cloned project cannot be used directly. Thank you！

**Comment by nkristina** [comment]
Hi,  I added the whole project to the PROJECT folder. Try to open the .sln file in that folder.
There are also some pictures on which tests are done. There is a picture named MyExampe.bmp, you should delete that picture and put the one you want with the same name.

You can change what operations you want to be done on your picture in the following lines of code:  lines 25-59 in _Main.cpp_

After running the code, the output picture will be in ImageEditor project folder (same as the original picture) named MyExample_RESULT.bmp

I hope this helps. If not, feel free to ask more here.
